### ISSUE TITLE
Any change to user info will cause an error

### ISSUE THREAD

**Issue by PedroLiu** [unias/docklet#93] opened 2016-05-07 07:28 UTC
Error info is below.
 File "/home/liupd/docklet/src/userManager.py", line 619, in modify
    self.set_nfs_quota(user_modify.username,res['data']['data'])
KeyError: 'data'

@zhongyehong , Please fix it

**Comment by zhongyehong** [comment] 2016-05-07 07:33
You should set the data value in admin page, e.g 100

**Comment by PedroLiu** [comment] 2016-05-07 16:21
If I install docklet without any extra configuration, is this a bug I will meet in any conditions?
I will add some code to report this reason to admin.

**Comment by zhongyehong** [comment] 2016-05-07 16:30
No need, I will add default value in upgrade.py later.

**Comment by caodg** [comment] 2016-05-07 23:16
@zhongyehong 

It is a bug, should be fixed in main code.
It is unreasonable to have to  run upgrade.py for a fresh install. 
The data field should have a default value, which can work for a default installation.

Upgrade.py should only be used for an already running install.

**Comment by zhongyehong** [comment] 2016-05-08 04:59
If you first time to install docklet, the default values of all quota will be set, include data quota.
The problem is  I add the data quota in upgrade.py, without setting default value of exists quota group, so I mean I will fix it.

**Comment by zhongyehong** [comment] 2016-05-09 04:54
Done

**Closed by zhongyehong** 2016-05-09 04:54 UTC
Labels: bug
